groups:
  - name: monitoring.rules
    rules:

      - alert: BaseDeDatosCaida
        expr: up{job="postgres_exporters"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exportador de Postgres caído ({{ $labels.instance }})"
          description: "El exportador de Postgres para {{ $labels.instance }} no está respondiendo."


      - alert: RedisCaido
        expr: up{job="redis_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Exportador de Redis caído ({{ $labels.instance }})"
          description: "El exportador de Redis para {{ $labels.instance }} no está respondiendo."


      - alert: UsoAltoDeCPU
        expr: (1 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) / avg by (instance) (rate(node_cpu_seconds_total[2m])))) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU en {{ $labels.instance }}"
          description: "Uso de CPU superior al 90 % durante más de 2 minutos en {{ $labels.instance }}"

      - alert: ChatBotServicioCaido
        expr: up{job="services", instance=~"chatbot-service-.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Servicio de ChatBot caído ({{ $labels.instance }})"
          description: "El servicio de ChatBot {{ $labels.instance }} no está respondiendo. Se necesita verificación inmediata."

      - alert: ChatBotTiempoRespuestaAlto
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="services", instance=~"chatbot-service-.*"}[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Tiempo de respuesta alto en ChatBot ({{ $labels.instance }})"
          description: "El percentil 95 del tiempo de respuesta del ChatBot en {{ $labels.instance }} supera los 5 segundos."

      - alert: ChatBotTasaErroresAlta
        expr: rate(http_requests_total{job="services", instance=~"chatbot-service-.*", status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Tasa de errores alta en ChatBot ({{ $labels.instance }})"
          description: "La tasa de errores 5xx en {{ $labels.instance }} supera el 5% durante los últimos 5 minutos."

      - alert: ChatBotBaseDatosCaida
        expr: up{job="postgres_exporters", instance="postgres-exporter-chatbot:9187"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Base de datos del ChatBot caída"
          description: "La base de datos del ChatBot no está respondiendo. El servicio puede estar degradado."
