#!/usr/bin/env sh
set -eu

# Ensure backups dir exists
mkdir -p /backups
chown -R 1000:1000 /backups || true

# If running one-off backup
if [ "${BACKUP_ONCE:-0}" = "1" ]; then
  echo "[entrypoint] Running one-off backup"
  /app/backup.sh
  exit 0
fi

# Create crontab line from BACKUP_SCHEDULE
SCHEDULE="${BACKUP_SCHEDULE:-0 3 * * *}"
# Alpine uses /etc/crontabs/root
echo "# Backup cron generated by entrypoint" > /etc/crontabs/root
echo "${SCHEDULE} /app/backup.sh >> /var/log/pg-backup.log 2>&1" >> /etc/crontabs/root

# Start crond in foreground
echo "[entrypoint] Starting crond with schedule: ${SCHEDULE}"
# Show current crontab
cat /etc/crontabs/root

# Tail the log in background so docker logs show it
touch /var/log/pg-backup.log

# run an initial backup at startup if flag set
if [ "${BACKUP_AT_STARTUP:-0}" = "1" ]; then
  echo "[entrypoint] Performing initial backup at startup"
  /app/backup.sh >> /var/log/pg-backup.log 2>&1 || true
fi

# Start crond
crond -f -d 8
